
auth.token=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

defaults.org=affinity-labs-0i
defaults.project=react-native

defaults.url=https://sentry.io/
